language: node_js
branches:
    only:
        - master
        - development
        - /(release).*/
env:
    global:
        - ENCRYPTION_LABEL: 98a7d362e1e4
    matrix:
        - BUILD=true TEST=false
        # - BUILD=false TEST=true BROWSER=chrome
        # - BUILD=false TEST=true BROWSER=ie
        # - BUILD=false TEST=true BROWSER=edge
        # - BUILD=false TEST=true BROWSER=firefox
node_js:
    - stable
addons:
    browserstack:
        username: "bertrandberthelo1"
        access_key:
            secure: "kB8iXiydT+xheyHox2zwq/1k75uUmF+F2b9k76Nhbb001Mh5608kzhH9xXFM+BUyM1pm3LImF+vYcSfKMYlDn/KBB7s9p8TJfwC/obbmtWJucSjtRiVo9aOOa7Ox2M+ACb0rsLpvzFRiHtYo0HZNFVkIfvqZN389Imm6UCOXsyo="
before_install:
    - openssl aes-256-cbc -K $encrypted_65cc4fd09d02_key -iv $encrypted_65cc4fd09d02_iv -in travis_deploy.enc -out travis_deploy -d
    - npm install -g gulp
    - chmod 600 travis_deploy
    - eval `ssh-agent -s`
    - ssh-add travis_deploy
install:
    - npm install
script:
    - if [[ "$BUILD" = "true" ]]; then npm run build ; fi
    - if [[ "$BUILD" = "true" ]]; then npm run deploy ; fi
    - if [[ "$BUILD" = "true" ]]; then npm run dist ; fi
    - if [[ "$TEST" = "true" &&  "$TRAVIS_BRANCH" != "master" &&  "$TRAVIS_BRANCH" != "development" ]]; then npm test ; fi
