language: node_js
env:
  global:
    - ENCRYPTION_LABEL:"b4d359c9e142"
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_b4d359c9e142_key -iv $encrypted_b4d359c9e142_iv
  -in key_travis.enc -out build/key_travis -d
- npm install -g gulp
install: npm install
script: cd build && gulp
after_success:
- npm run-script deploy-dev
- npm test
